### ISSUE TITLE
[Bug] Markdown render not working

### ISSUE THREAD

**Issue by ecwu** [heimoshuiyu/chatgpt-api-web#6]
![image](https://github.com/user-attachments/assets/5e211f84-33b4-4a2c-8266-e33251e0d7af)

Markdown render is not working.

**Comment by heimoshuiyu** [comment]
blame react 19 :(
 https://github.com/heimoshuiyu/chatgpt-api-web/blob/a56aa0205db2405bf4c0c1e4dd1b94c3a89270ed/src/message.tsx#L159
and here https://github.com/remarkjs/react-markdown/pull/879
